.nh
.TH "HUGO-MOD-TIDY" "1" "Sep 2023" "Hugo 0.119.0-DEV" "Hugo Manual"

.SH NAME
.PP
hugo-mod-tidy - Remove unused entries in go.mod and go.sum.


.SH SYNOPSIS
.PP
\fBhugo mod tidy [flags] [args]\fP


.SH DESCRIPTION
.PP
Remove unused entries in go.mod and go.sum.


.SH OPTIONS
.PP
\fB-b\fP, \fB--baseURL\fP=""
	hostname (and path) to the root, e.g. https://spf13.com/

.PP
\fB--cacheDir\fP=""
	filesystem path to cache directory

.PP
\fB-c\fP, \fB--contentDir\fP=""
	filesystem path to content directory

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for tidy

.PP
\fB-t\fP, \fB--theme\fP=[]
	themes to use (located in /themes/THEMENAME/)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--clock\fP=""
	set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00

.PP
\fB--config\fP=""
	config file (default is hugo.yaml|json|toml)

.PP
\fB--configDir\fP="config"
	config dir

.PP
\fB--debug\fP[=false]
	debug output

.PP
\fB-d\fP, \fB--destination\fP=""
	filesystem path to write files to

.PP
\fB-e\fP, \fB--environment\fP=""
	build environment

.PP
\fB--ignoreVendorPaths\fP=""
	ignores any _vendor for module paths matching the given Glob pattern

.PP
\fB--logLevel\fP=""
	log level (debug|info|warn|error)

.PP
\fB--quiet\fP[=false]
	build in quiet mode

.PP
\fB-s\fP, \fB--source\fP=""
	filesystem path to read files relative from

.PP
\fB--themesDir\fP=""
	filesystem path to themes directory

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBhugo-mod(1)\fP
