.nh
.TH "HUGO" "1" "Sep 2023" "Hugo 0.119.0-DEV" "Hugo Manual"

.SH NAME
.PP
hugo - hugo builds your site


.SH SYNOPSIS
.PP
\fBhugo [flags]\fP


.SH DESCRIPTION
.PP
hugo is the main command, used to build your Hugo site.

.PP
Hugo is a Fast and Flexible Static Site Generator
built with love by spf13 and friends in Go.

.PP
Complete documentation is available at https://gohugo.io/.


.SH OPTIONS
.PP
\fB-b\fP, \fB--baseURL\fP=""
	hostname (and path) to the root, e.g. https://spf13.com/

.PP
\fB-D\fP, \fB--buildDrafts\fP[=false]
	include content marked as draft

.PP
\fB-E\fP, \fB--buildExpired\fP[=false]
	include expired content

.PP
\fB-F\fP, \fB--buildFuture\fP[=false]
	include content with publishdate in the future

.PP
\fB--cacheDir\fP=""
	filesystem path to cache directory

.PP
\fB--cleanDestinationDir\fP[=false]
	remove files from destination not found in static directories

.PP
\fB--clock\fP=""
	set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00

.PP
\fB--config\fP=""
	config file (default is hugo.yaml|json|toml)

.PP
\fB--configDir\fP="config"
	config dir

.PP
\fB-c\fP, \fB--contentDir\fP=""
	filesystem path to content directory

.PP
\fB--debug\fP[=false]
	debug output

.PP
\fB-d\fP, \fB--destination\fP=""
	filesystem path to write files to

.PP
\fB--disableKinds\fP=[]
	disable different kind of pages (home, RSS etc.)

.PP
\fB--enableGitInfo\fP[=false]
	add Git revision, date, author, and CODEOWNERS info to the pages

.PP
\fB-e\fP, \fB--environment\fP=""
	build environment

.PP
\fB--forceSyncStatic\fP[=false]
	copy all files when static is changed.

.PP
\fB--gc\fP[=false]
	enable to run some cleanup tasks (remove unused cache files) after the build

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for hugo

.PP
\fB--ignoreCache\fP[=false]
	ignores the cache directory

.PP
\fB--ignoreVendorPaths\fP=""
	ignores any _vendor for module paths matching the given Glob pattern

.PP
\fB-l\fP, \fB--layoutDir\fP=""
	filesystem path to layout directory

.PP
\fB--logLevel\fP=""
	log level (debug|info|warn|error)

.PP
\fB--minify\fP[=false]
	minify any supported output format (HTML, XML etc.)

.PP
\fB--noBuildLock\fP[=false]
	don't create .hugo_build.lock file

.PP
\fB--noChmod\fP[=false]
	don't sync permission mode of files

.PP
\fB--noTimes\fP[=false]
	don't sync modification time of files

.PP
\fB--panicOnWarning\fP[=false]
	panic on first WARNING log

.PP
\fB--poll\fP=""
	set this to a poll interval, e.g --poll 700ms, to use a poll based approach to watch for file system changes

.PP
\fB--printI18nWarnings\fP[=false]
	print missing translations

.PP
\fB--printMemoryUsage\fP[=false]
	print memory usage to screen at intervals

.PP
\fB--printPathWarnings\fP[=false]
	print warnings on duplicate target paths etc.

.PP
\fB--printUnusedTemplates\fP[=false]
	print warnings on unused templates.

.PP
\fB--quiet\fP[=false]
	build in quiet mode

.PP
\fB--renderToMemory\fP[=false]
	render to memory (only useful for benchmark testing)

.PP
\fB-s\fP, \fB--source\fP=""
	filesystem path to read files relative from

.PP
\fB--templateMetrics\fP[=false]
	display metrics about template executions

.PP
\fB--templateMetricsHints\fP[=false]
	calculate some improvement hints when combined with --templateMetrics

.PP
\fB-t\fP, \fB--theme\fP=[]
	themes to use (located in /themes/THEMENAME/)

.PP
\fB--themesDir\fP=""
	filesystem path to themes directory

.PP
\fB--trace\fP=""
	write trace to \fB\fCfile\fR (not useful in general)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output

.PP
\fB-w\fP, \fB--watch\fP[=false]
	watch filesystem for changes and recreate as needed


.SH SEE ALSO
.PP
\fBhugo-completion(1)\fP, \fBhugo-config(1)\fP, \fBhugo-convert(1)\fP, \fBhugo-deploy(1)\fP, \fBhugo-env(1)\fP, \fBhugo-gen(1)\fP, \fBhugo-import(1)\fP, \fBhugo-list(1)\fP, \fBhugo-mod(1)\fP, \fBhugo-new(1)\fP, \fBhugo-server(1)\fP, \fBhugo-version(1)\fP
