.nh
.TH "HUGO-SERVER" "1" "Sep 2023" "Hugo 0.119.0-DEV" "Hugo Manual"

.SH NAME
.PP
hugo-server - A high performance webserver


.SH SYNOPSIS
.PP
\fBhugo server [command] [flags]\fP


.SH DESCRIPTION
.PP
Hugo provides its own webserver which builds and serves the site.
While hugo server is high performance, it is a webserver with limited options.

.PP
\&'hugo server' will avoid writing the rendered and served content to disk,
preferring to store it in memory.

.PP
By default hugo will also watch your files for any changes you make and
automatically rebuild the site. It will then live reload any open browser pages
and push the latest content to them. As most Hugo sites are built in a fraction
of a second, you will be able to save and see your changes nearly instantly.


.SH OPTIONS
.PP
\fB--appendPort\fP[=true]
	append port to baseURL

.PP
\fB-b\fP, \fB--baseURL\fP=""
	hostname (and path) to the root, e.g. https://spf13.com/

.PP
\fB--bind\fP="127.0.0.1"
	interface to which the server will bind

.PP
\fB-D\fP, \fB--buildDrafts\fP[=false]
	include content marked as draft

.PP
\fB-E\fP, \fB--buildExpired\fP[=false]
	include expired content

.PP
\fB-F\fP, \fB--buildFuture\fP[=false]
	include content with publishdate in the future

.PP
\fB--cacheDir\fP=""
	filesystem path to cache directory

.PP
\fB--cleanDestinationDir\fP[=false]
	remove files from destination not found in static directories

.PP
\fB-c\fP, \fB--contentDir\fP=""
	filesystem path to content directory

.PP
\fB--disableBrowserError\fP[=false]
	do not show build errors in the browser

.PP
\fB--disableFastRender\fP[=false]
	enables full re-renders on changes

.PP
\fB--disableKinds\fP=[]
	disable different kind of pages (home, RSS etc.)

.PP
\fB--disableLiveReload\fP[=false]
	watch without enabling live browser reload on rebuild

.PP
\fB--enableGitInfo\fP[=false]
	add Git revision, date, author, and CODEOWNERS info to the pages

.PP
\fB--forceSyncStatic\fP[=false]
	copy all files when static is changed.

.PP
\fB--gc\fP[=false]
	enable to run some cleanup tasks (remove unused cache files) after the build

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for server

.PP
\fB--ignoreCache\fP[=false]
	ignores the cache directory

.PP
\fB-l\fP, \fB--layoutDir\fP=""
	filesystem path to layout directory

.PP
\fB--liveReloadPort\fP=-1
	port for live reloading (i.e. 443 in HTTPS proxy situations)

.PP
\fB--meminterval\fP="100ms"
	interval to poll memory usage (requires --memstats), valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".

.PP
\fB--memstats\fP=""
	log memory usage to this file

.PP
\fB--minify\fP[=false]
	minify any supported output format (HTML, XML etc.)

.PP
\fB--navigateToChanged\fP[=false]
	navigate to changed content file on live browser reload

.PP
\fB--noBuildLock\fP[=false]
	don't create .hugo_build.lock file

.PP
\fB--noChmod\fP[=false]
	don't sync permission mode of files

.PP
\fB--noHTTPCache\fP[=false]
	prevent HTTP caching

.PP
\fB--noTimes\fP[=false]
	don't sync modification time of files

.PP
\fB--panicOnWarning\fP[=false]
	panic on first WARNING log

.PP
\fB--poll\fP=""
	set this to a poll interval, e.g --poll 700ms, to use a poll based approach to watch for file system changes

.PP
\fB-p\fP, \fB--port\fP=1313
	port on which the server will listen

.PP
\fB--printI18nWarnings\fP[=false]
	print missing translations

.PP
\fB--printMemoryUsage\fP[=false]
	print memory usage to screen at intervals

.PP
\fB--printPathWarnings\fP[=false]
	print warnings on duplicate target paths etc.

.PP
\fB--printUnusedTemplates\fP[=false]
	print warnings on unused templates.

.PP
\fB--renderStaticToDisk\fP[=false]
	serve static files from disk and dynamic files from memory

.PP
\fB--renderToDisk\fP[=false]
	serve all files from disk (default is from memory)

.PP
\fB--templateMetrics\fP[=false]
	display metrics about template executions

.PP
\fB--templateMetricsHints\fP[=false]
	calculate some improvement hints when combined with --templateMetrics

.PP
\fB-t\fP, \fB--theme\fP=[]
	themes to use (located in /themes/THEMENAME/)

.PP
\fB--tlsAuto\fP[=false]
	generate and use locally-trusted certificates.

.PP
\fB--tlsCertFile\fP=""
	path to TLS certificate file

.PP
\fB--tlsKeyFile\fP=""
	path to TLS key file

.PP
\fB--trace\fP=""
	write trace to \fB\fCfile\fR (not useful in general)

.PP
\fB-w\fP, \fB--watch\fP[=true]
	watch filesystem for changes and recreate as needed


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB--clock\fP=""
	set the clock used by Hugo, e.g. --clock 2021-11-06T22:30:00.00+09:00

.PP
\fB--config\fP=""
	config file (default is hugo.yaml|json|toml)

.PP
\fB--configDir\fP="config"
	config dir

.PP
\fB--debug\fP[=false]
	debug output

.PP
\fB-d\fP, \fB--destination\fP=""
	filesystem path to write files to

.PP
\fB-e\fP, \fB--environment\fP=""
	build environment

.PP
\fB--ignoreVendorPaths\fP=""
	ignores any _vendor for module paths matching the given Glob pattern

.PP
\fB--logLevel\fP=""
	log level (debug|info|warn|error)

.PP
\fB--quiet\fP[=false]
	build in quiet mode

.PP
\fB-s\fP, \fB--source\fP=""
	filesystem path to read files relative from

.PP
\fB--themesDir\fP=""
	filesystem path to themes directory

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
.PP
\fBhugo(1)\fP, \fBhugo-server-trust(1)\fP
