The contents of the updated `hugo.1` file:

.nh
.TH "HUGO" "1" "Sep 2023" "Hugo 0.120.0-DEV" "Hugo Manual"

.SH NAME
.PP
hugo - hugo builds your site

...

.SH SEE ALSO
.PP
\fBhugo-completion(1)\fP, \fBhugo-config(1)\fP, \fBhugo-convert(1)\fP, \fBhugo-deploy(1)\fP, \fBhugo-env(1)\fP, \fBhugo-gen(1)\fP, \fBhugo-import(1)\fP, \fBhugo-list(1)\fP, \fBhugo-mod(1)\fP, \fBhugo-new(1)\fP, \fBhugo-server(1)\fP, \fBhugo-version(1)\fP
